# Generated by Django 5.0.4 on 2024-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_savat'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='image',
            field=models.ImageField(default=1, upload_to='products/shop'),
            preserve_default=False,
        ),
    ]
